config/routes.rb
Brazil2014::Application.routes.draw do
  root 'games#index'

  get  'auth/twitter/callback', to: 'sessions#create'
  get  'auth/failure',        to: redirect('/')  
  get  'signout',             to: 'sessions#destroy',       as: 'signout'
  get  'auth/twitter',                                      as: 'signin'
  get  'cookies',             to: 'static_pages#cookies',   as: 'cookies'

  get  'players',             to: 'players#index',          as: 'players'

  post 'games/:game_id/performance_records/:performance_record_id/ratings/', to: 'ratings#create', as: 'game_performance_record_ratings'

  get 'users/:user_id/games/:game_id', to: 'ratings#index', as: 'user_game'
  resources :users, only: :show

  resources :teams do
    resources :players, except: :index
  end

  resources :games do
    resources :performance_records, only: [:new, :create, :destroy]
  end

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  # Relationships
  belongs_to :performance_record
  belongs_to :user

  # Validation
  validates :performance_record_id, presence: true
  validates :user_id,               presence: true, uniqueness:   { scope: :performance_record_id }
  validates :rating,                presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :signed_in_user, only: :create
  before_action :set_record,     only: :create
  before_action :set_user,       only: :index
  before_action :set_game,       only: :index
  before_action :set_records,    only: :index

  def create
    @rating = Rating.new(rating_params)
    @rating.performance_record = @record
    @rating.user = current_user
    if @rating.valid? and @record.rate!(params[:rating][:rating].to_i) and @rating.save
      respond_to do |format|
        format.js do
          @rating
          render 'new_rating'
        end
      end
    else
      respond_to do |format|
        format.js   { render 'new_rating_errors', object: @rating }
      end
    end
  end

  def index

  end

  private

    def rating_params
      params.require(:rating).permit(:rating)
    end

    def set_record
      @record = PerformanceRecord.find(params[:performance_record_id])
    end

    def set_game
      @game = Game.find(params[:game_id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def set_records
      @home_records = @game.performance_records.where(as_home_player: true).order(:starting)
      @away_records = @game.performance_records.where(as_home_player: false).order(:starting)
    end

end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_player_rating.html.erb
<% if !signed_in? or (rating = Rating.where(performance_record_id: record.id, user_id: current_user.id).first).nil? %>
  <%= form_tag(game_performance_record_ratings_path(game, record), remote: true, class: 'form-inline', role: 'form' ) do %>
  <div class="input-group">
    <input class="form-control input-sm" id="rating_rating" max="10" min="0" name="rating[rating]" type="number" placeholder="Nota">
    <span class="input-group-btn">
      <%= submit_tag('Votar', class: 'btn btn-default btn-sm') if signed_in? %>
      <% unless signed_in? %>
        <button class="btn primary-green btn-sm" data-toggle="modal" data-target="#signin-modal">
        Votar
        </button>
      <% end %>
    </span>
  </div>
  <% end %>
<% else %>
  <%= render 'ratings/rating', rating: rating %>
<% end %>

app/views/ratings/_rating.html.erb
<span class="label label-rating label-<%= class_for_rating(rating.rating) %>" data-toggle="tooltip" data-placement="top" title="Tu Nota">
    <%= rating.rating %>
</span>

app/views/ratings/index.html.erb
<% provide(:title, "Puntuaciones de #{@user} del #{@game}") %>
<% content_for :extra_meta do %> 
  <%= render 'shared/twitter_cards', user: @user, game: @game %>
<% end %>
<section id="game_<%= @game.id %>">
  <section class="page-header">
    <h1 class="hidden-xs"><%= image_for(@game.home_team, :large) %> <%= @game.home_team %> <%= @game.result %> <%= @game.away_team %> <%= image_for(@game.away_team, :large) %> <small class="hidden-xs">Puntuaciones de <%= @user %></small></h1>
    <h1 class="visible-xs text-center"><%= image_for(@game.home_team, :large) %> <%= @game.result %>  <%= image_for(@game.away_team, :large) %></h1>

  </section>
  <nav>
    <ol class="breadcrumb">
      <li>Usuarios</a></li>
      <li><a href="<%= user_path(@user, @game) %>"><%= @user %></a></li>
      <li class="active"><%= @game %></li>
    </ol>
  </nav>
  <% if @game.performance_records.count > 0 %>
  <section id="game-stats">
    <div class="row">
      <div class="col-md-6 col-xs-12" id="home_team_records">
        <%= render 'users/game_records', records: @home_records, user: @user, home: true %>
      </div>
      <div class="col-md-6 col-xs-12" id="away_team_records">
        <%= render 'users/game_records', records: @away_records, user: @user, home: false %>
      </div>
    </div>
  </section>
  <footer class="text-center">
    <a href="https://twitter.com/share" class="twitter-share-button" data-text="Mira las notas de <%= @user %> para el #<%= @game.home_team %> - #<%= @game.away_team %>" data-via="NotasDelMundial" data-lang="es" data-size="large" data-related="antoniobg87" data-hashtags="WorldCup2014,Brasil2014">Twittear</a>
  </footer>
  <% end %>
</section>

app/views/ratings/new_rating.js.erb
$("#rate_record_<%= @rating.performance_record.id %> > .rate-form-cell").html("<%= escape_javascript(render 'ratings/rating', rating: @rating) %>")

app/views/ratings/new_rating_errors.js.erb
$("#game-stats").prepend("<%= escape_javascript(render('shared/error_messages', object: @rating)) %>");