config/routes.rb
Brazil2014::Application.routes.draw do
  root 'games#index'

  get  'auth/twitter/callback', to: 'sessions#create'
  get  'auth/failure',        to: redirect('/')  
  get  'signout',             to: 'sessions#destroy',       as: 'signout'
  get  'auth/twitter',                                      as: 'signin'
  get  'cookies',             to: 'static_pages#cookies',   as: 'cookies'

  get  'players',             to: 'players#index',          as: 'players'

  post 'games/:game_id/performance_records/:performance_record_id/ratings/', to: 'ratings#create', as: 'game_performance_record_ratings'

  get 'users/:user_id/games/:game_id', to: 'ratings#index', as: 'user_game'
  resources :users, only: :show

  resources :teams do
    resources :players, except: :index
  end

  resources :games do
    resources :performance_records, only: [:new, :create, :destroy]
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :performance_records
  has_many :players, through: :performance_records
  belongs_to :home_team, class_name: 'Team'
  belongs_to :away_team, class_name: 'Team'
  
  # Filters
  default_scope -> { order('date DESC') }

  # Validation
  validates :date,         presence: true
  validates :home_team_id, presence: true
  validates :away_team_id, presence: true
  validates :round,        presence: true

  def home_players
    players.where(team_id: home_team_id)
  end

  def away_players
    players.where(team_id: away_team_id)
  end

  def publish!
    self.update_attributes(published: true)
  end

  def unpublish!
    self.update_attributes(published: false)
  end

  def finish!
    self.update_attributes(finished: true)
  end

  def unfinish!
    self.update_attributes(finished: false)
  end

  def to_s
    if result.blank?
      "#{home_team} - #{away_team}"
    else
      "#{home_team} #{result} #{away_team}"
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :user_is_admin,  except: [:index, :show]
  before_action :set_game,       except: [:index, :new, :create]
  before_action :set_records,    only:   :show
  before_action :set_rounds,     only:   [:new, :edit]

  def index
    conditions = get_conditions
    @games = Game.where(conditions).paginate(page: params[:page], per_page: 20 )
  end

  def show
  end

  def new
    @teams = Team.all.collect { |t| [t.name, t.id ] }
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      flash[:success] = "Game created successfully"
      redirect_to game_path(@game)
    else
      render 'new'
    end
  end

  def edit
    @teams = Team.all.collect { |t| [t.name, t.id ] }
  end

  def update
    if @game.update_attributes(game_params)
      flash[:success] = "Game updated successfully"
      redirect_to game_path(@game)
    else
      render 'edit'
    end
  end

  def destroy
    @game.destroy
    flash[:success] = "Game #{@game} has been deleted successfully"
    redirect_to games_path
  end

  private

    def get_conditions
      conditions = {}
      conditions[:round] = params[:round] if params[:round]
      conditions[:published] = true unless signed_in_as_admin?
      conditions
    end

    def game_params
      params.require(:game).permit(:date, :round, :result, :home_team_id, :away_team_id, :published, :finished)
    end

    def set_game
      @game = Game.find(params[:id])
    end

    def set_records
      @home_records = @game.performance_records.where(as_home_player: true).order(:starting)
      @away_records = @game.performance_records.where(as_home_player: false).order(:starting)
    end

    def set_teams
      @home_team = Team.find(params[:game][:home_team_id])
      @away_team = Team.find(params[:game][:away_team_id])
    end

    def set_rounds
      @rounds = [["Grupo A", "Grupo A"], ["Grupo B", "Grupo B"], ["Grupo C", "Grupo C"], ["Grupo D", "Grupo D"], ["Grupo E", "Grupo E"], ["Grupo F", "Grupo F"], ["Grupo G", "Grupo G"], ["Grupo H", "Grupo H"], ["1/8", "1/8"], ["1/4", "1/4"], ["Semifinales", "Semifinales"], ["3º/4º", "3º/4º"], ["Final", "Final"]]
    end

end

app/helpers/games_helper.rb
module GamesHelper
  def class_for_game(game)
    game.finished? ? 'active' : ''
  end

  def render_game_body(game)
    if game.finished?
      render 'games/finished_game_body', game: game
    else
      render 'games/not_finished_game_body', game: game
    end
  end

  def time_for_game(date)
    day = day(date)
    if day.nil?
      date.to_s(:for_games_date_time)
    else
      "#{day} #{date.to_s(:for_games_time)}"
    end
  end

  def day(date)
    today = Time.now
    if date.month == today.month or date.year == today.year
      case date.day
      when today.day
        day = "Hoy"
      when today.day + 1
        day = "Mañana"
      when today.day - 1
        day = "Ayer"
      end
    end
  end

  def game_is_finished(game)
    game.finished? ? "Finalizado" : "Por jugar"
  end

end

app/views/games/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
<div class="form-group">
  <%= f.label :date, 'Date *' %>
  <%= f.datetime_select :date, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :home_team_id, 'Home Team *' %>
  <%= f.select :home_team_id, @teams, {include_blank: "Select a team"}, { class: "form-control" } %>
</div>

<div class="form-group">
  <%= f.label :away_team_id, 'Away Team *' %>
  <%= f.select :away_team_id, @teams, {include_blank: "Select a team"}, { class: "form-control" } %>
</div>

<div class="form-group">
  <%= f.label :round, 'Round *' %>
  <%= f.select :round, @rounds, { include_blank: "Select a round"}, { class: "form-control" } %>
</div>

<div class="form-group">
  <%= f.label :result, 'Result' %>
  <%= f.text_field :result, class: "form-control", placeholder: 'Enter the result' %>
</div>

<div class="form-group">
  <label>Options</label>
  <label for="game_published" class="checkbox-inline">
    <%= f.check_box :published %>
    Published
  </label>
  <label for="game_finished" class="checkbox-inline">
    <%= f.check_box :finished %>
    Finished
  </label>
</div>


<%= f.submit 'Save', class: 'btn btn-default' %>

app/views/games/_game_records.html.erb
<div class="table-responsive">
  <h4 class="text-center"><%= home ? @game.home_team : @game.away_team %></h4>
  <table class="table table-condensed table-hover table-bordered game-stats-table">
    <thead>
      <tr>
        <th>#</th>
        <th>Rol</th>
        <th>Jugador</th>
        <th></th>
        <th class="hidden-xs"></th>
        <th class="hidden-xs"></th>
        <th class="hidden-xs"></th>
        <th class="text-center">Media</th>
        <th class="text-center">Tu Nota</th>
      </tr>
    </thead>
    <tbody>
    <% records.each do |record| %>
      <tr class="<%= class_for_record(record) %>" id="rate_record_<%= record.id %>">
        <td><%= record.player.number %></td>
        <td><%= record.player.position %></td>
        <td><%= link_to record.player, team_player_path(record.player.team, record.player) %></td>
        <td><%= print_goals(record.goals) %></td>
        <td class="hidden-xs">
          <span class="label label-yellow" data-toggle="tooltip" data-placement="top" title="Tarjeta Amarilla"><%= yellow_cards(record.yellow_cards) %></span>
          <span class="label label-red" data-toggle="tooltip" data-placement="top" title="Tarjeta Roja"><%= red_card(record.red_cards) %></span>
        </td>
        <td class="hidden-xs"><i class="fa fa-clock-o fa-minutes" data-toggle="tooltip" data-placement="top" title="Minutos Jugados"></i> <%= record.minutes %>'</td>
        <td class="hidden-xs"><%= substitution(record) %></td>
        <td class="text-center">
          <span class="label label-rating label-<%= class_for_rating(record.rating_avg) %>" data-toggle="tooltip" data-placement="top" title="Nota Media">
            <%= record_rating(record) %>
          </span>
        </td>
        <td class="rate-form-cell text-center">
          <%= render 'ratings/player_rating', record: record, game: @game %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/games/_games.html.erb
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Fecha</th>
        <th class="text-center" colspan="3">Partido</th>
        <th class="hidden-xs">Fase</th>
        <th class="hidden-xs">Estado</th>
      </tr>
    </thead>
    <tbody>
      <% games.each do |game| %>
      <% clickable = (game.performance_records.any? or signed_in_as_admin?) %>
      <tr class="<%= class_for_game(game) %> <%= 'tr-clickable' if clickable %>" <%= "href=#{game_path(game)}" if clickable %> >
        <td style="width:auto;white-space:nowrap">
          <i class="fa fa-calendar"></i>
          <%= time_for_game(game.date) %>
        </td>
        <td class="text-right">
          <%= image_for(game.home_team, :small) %>
          <% if game.performance_records.any? or signed_in_as_admin? %>
            <%= link_to game.home_team, game_path(game) %>
          <% else %>
            <%=  link_to game.home_team, team_path(game.home_team) %>
          <% end %>
        </td>
        <td class="text-center">
          <% if game.performance_records.any? %>
            <%= link_to game.result, game_path(game) %>
          <% else %>
            <%=  game.result %>
          <% end %>        
        </td>
        <td>
          <% if game.performance_records.any? or signed_in_as_admin? %>
            <%= link_to game.away_team, game_path(game) %>
          <% else %>
            <%=  link_to game.away_team, team_path(game.away_team) %>
          <% end %>
          <%= image_for(game.away_team, :small) %>
        </td>
        <td class="hidden-xs"><%= game.round %></td>
        <td class="hidden-xs">
          <%= game_is_finished(game) %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/games/_index_admin_menu.html.erb
<section class="panel panel-primary">
  <section class="panel-heading">
    <h3 class="panel-title">Administration</h3>
  </section>
  <section class="panel-body">
    <ul class="list-inline">
      <li>
        <a href="<%= new_game_path %>">
          <i class="fa fa-plus"></i>
          New Game
        </a>
      </li>
    </ul>
  </section>
</section>

app/views/games/_show_admin_menu.html.erb
<section class="panel panel-primary">
  <section class="panel-heading">
    <h3 class="panel-title">Administration</h3>
  </section>
  <section class="panel-body">
    <ul class="list-inline">
      <li>
        <a href="<%= new_game_performance_record_path(@game) %>">
          <i class="fa fa-plus"></i>
          Add Player
        </a>
      </li>
      <li>
        <a href="<%= edit_game_path(@game) %>">
          <i class="fa fa-edit"></i>
          Edit
        </a>
      </li>
      <li>
        <%= link_to content_tag(:i, "", class: "fa fa-trash-o") << " Delete", game_path(@game), method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    </ul>
  </section>
</section>

app/views/games/edit.html.erb
<%= form_for @game, html: { role: 'form' } do |f| %>
  <%= render 'fields', f: f %>
<% end %>

app/views/games/index.html.erb
<% provide(:title, "Partidos #{params[:round]}") %>

<section id="games">
  <section class="page-header">
    <h1>Partidos <small class="hidden-xs"><%= params[:round] || 'Todos' %></small></h1>
  </section>
  <%= render 'index_admin_menu' if signed_in_as_admin? %>
  <nav>
    <ol class="breadcrumb">
      <li class="<%= 'active' if params[:round] %>"><%= params[:round] ? (link_to 'Partidos', games_path) : 'Partidos' %></li>
      <%= content_tag(:li, params[:round], class: 'active') if params[:round] %>
    </ol>
  </nav>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#round-filters">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand visible-xs" href="#">Filtros: </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse text-right" id="round-filters">
        <ul class="nav navbar-nav">
          <li class="<%= 'active' unless params[:round] %>"><a href="<%= games_path %>">Todos</a></li>
          <li class="<%= 'active' if params[:round] == "Grupo A" %>"><a href="<%= games_path(round: "Grupo A") %>">A</a></li>
          <li class="<%= 'active' if params[:round] == "Grupo B" %>"><a href="<%= games_path(round: "Grupo B") %>">B</a></li>
          <li class="<%= 'active' if params[:round] == "Grupo C" %>"><a href="<%= games_path(round: "Grupo C") %>">C</a></li>
          <li class="<%= 'active' if params[:round] == "Grupo D" %>"><a href="<%= games_path(round: "Grupo D") %>">D</a></li>
          <li class="<%= 'active' if params[:round] == "Grupo E" %>"><a href="<%= games_path(round: "Grupo E") %>">E</a></li>
          <li class="<%= 'active' if params[:round] == "Grupo F" %>"><a href="<%= games_path(round: "Grupo F") %>">F</a></li>
          <li class="<%= 'active' if params[:round] == "Grupo G" %>"><a href="<%= games_path(round: "Grupo G") %>">G</a></li>
          <li class="<%= 'active' if params[:round] == "Grupo H" %>"><a href="<%= games_path(round: "Grupo H") %>">H</a></li>
          <li class="disabled"><a href="#">|</a></li>
          <li class="<%= 'active' if params[:round] == "1/8" %>"><a href="<%= games_path(round: "1/8") %>">1/8</a></li>
          <li class="<%= 'active' if params[:round] == "1/4" %>"><a href="<%= games_path(round: "1/4") %>">1/4</a></li>
          <li class="<%= 'active' if params[:round] == "Semifinales" %>"><a href="<%= games_path(round: "Semifinales") %>">Semifinales</a></li>
          <li class="<%= 'active' if params[:round] == "3º y 4º" %>"><a href="<%= games_path(round: "3º y 4º") %>">3º y 4º</a></li>
          <li class="<%= 'active' if params[:round] == "Final" %>"><a href="<%= games_path(round: "Final") %>">Final</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <section id="game-list">
    <%= render 'games', games: @games %>
    <div class="container text-center">
      <%= will_paginate @games, previous_label: content_tag(:i, '', class: 'fa fa-chevron-left'), next_label: content_tag(:i, '', class: 'fa fa-chevron-right'), renderer: BootstrapPagination::Rails %>
    </div>
  </section>
</section>

app/views/games/new.html.erb
<%= form_for @game, html: { role: 'form' } do |f| %>
  <%= render 'fields', f: f %>
<% end %>

app/views/games/show.html.erb
<% provide(:title, @game) %>
<% content_for(:extra_meta) do %>
  <%= render 'shared/twitter_cards', game: @game, user: current_user %>
<% end %>
<section id="game_<%= @game.id %>">
  <section class="page-header">
    <h1 class="hidden-xs"><%= image_for(@game.home_team, :large) %> <%= @game %> <%= image_for(@game.away_team, :large) %> <small><%= time_for_game(@game.date) %></small></h1>
    <h1 class="visible-xs"><%= image_for(@game.home_team, :large) %> <%= @game.result %> <%= image_for(@game.away_team, :large) %> <small><%= time_for_game(@game.date) %></small></h1>
  </section>
  <%= render 'show_admin_menu' if signed_in_as_admin? %>
  <nav>
    <ol class="breadcrumb">
      <li><a href="<%= games_path %>">Partidos</a></li>
      <li><a href="<%= games_path(round: @game.round) %>"><%= @game.round %></a></li>
      <li class="active"><%= @game %></li>
    </ol>
  </nav>
  <% if @game.performance_records.count > 0 %>
  <section id="game-stats">
    <div class="row">
      <div class="col-md-6 col-xs-12" id="home_team_records">
        <%= render 'game_records', records: @home_records, home: true %>
      </div>
      <div class="col-md-6 col-xs-12" id="away_team_records">
        <%= render 'game_records', records: @away_records, home: false %>
      </div>
    </div>
  </section>
  <footer class="text-center">
    <a href="https://twitter.com/share" class="twitter-share-button" data-text="Mira las notas del #<%= @game.home_team %> - #<%= @game.away_team %>" data-via="NotasDelMundial" data-lang="es" data-size="large" data-related="antoniobg87" data-hashtags="WorldCup2014,Brasil2014">Twittear</a>
  </footer>
  <% end %>
</section>