config/routes.rb
Brazil2014::Application.routes.draw do
  root 'games#index'

  get  'auth/twitter/callback', to: 'sessions#create'
  get  'auth/failure',        to: redirect('/')  
  get  'signout',             to: 'sessions#destroy',       as: 'signout'
  get  'auth/twitter',                                      as: 'signin'
  get  'cookies',             to: 'static_pages#cookies',   as: 'cookies'

  get  'players',             to: 'players#index',          as: 'players'

  post 'games/:game_id/performance_records/:performance_record_id/ratings/', to: 'ratings#create', as: 'game_performance_record_ratings'

  get 'users/:user_id/games/:game_id', to: 'ratings#index', as: 'user_game'
  resources :users, only: :show

  resources :teams do
    resources :players, except: :index
  end

  resources :games do
    resources :performance_records, only: [:new, :create, :destroy]
  end

end

app/models/player.rb
class Player < ActiveRecord::Base

  # Relationships
  belongs_to :team
  has_many   :performance_records
  has_many   :games, through: :performance_records
  belongs_to :position

  # Filters
  default_scope -> { order('team_id, position_id', 'number') }

  # Validations
  validates :team_id, presence: true

  def add_performance_data!(data)
    return if data.nil?
    self.goals += data[:goals].to_i if data[:goals]
    self.minutes += data[:minutes].to_i if data[:minutes]
    self.yellow_cards += data[:yellow_cards].to_i if data[:yellow_cards]
    self.red_cards += data[:red_cards].to_i if data[:red_cards]
    self.save if self.team.add_performance_data!(data)
      
  end

  def remove_performance_data!(data)
    return if data.nil?
    self.goals -= data[:goals].to_i if data[:goals]
    self.minutes -= data[:minutes].to_i if data[:minutes]
    self.yellow_cards -= data[:yellow_cards].to_i if data[:yellow_cards]
    self.red_cards -= data[:red_cards].to_i if data[:red_cards]
    self.save if self.team.remove_performance_data!(data)
  end

  def rate!(rating)
    self.rating_sum += rating
    self.rating_count += 1
    self.save if self.team.rate!(rating)
  end

  def rating_avg
    !rating_count.zero? ? (rating_sum.to_f / rating_count).round(2) : 0
  end

  def games_played
    games.count
  end

  def to_s
    name
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :user_is_admin,   except: [:index, :show]
  before_action :set_player,      except: [:index, :new, :create]
  before_action :set_team,        except: :index
  before_action :set_positions,   only:   [:new, :edit]

  def index
    @players = if params[:position]
      Player.find_all_by_position_id(params[:position])
    else
      Player.all
    end.paginate(page: params[:page], per_page: 30 )
  end

  def show
  end

  def new
    @positions = Position.all.collect { |p| [p.code, p.id ] }
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    @player.team = @team
    if @player.save
      flash[:success] = "Player #{@player} created successfully"
      redirect_to team_path(@player.team)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @player.update_attributes(player_params)
      flash[:success] = "Player updated successfully"
      redirect_to team_player_path(@team,@player)
    else
      render 'edit'
    end
  end

  def destroy
    @player.destroy
    flash[:success] = "Player #{@player} has ben deleted successfully"
    redirect_to @player.team
  end


  private

    def set_positions
      @positions = Position.all.collect { |p| [p.code, p.id ] }
    end

    def set_team
      @team = Team.find(params[:team_id])
    end

    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:name, :number, :position_id, :team_id)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
  CLASS_FOR_POSITION = { 
    'POR' => 'warning', 
    'DEF' => 'danger', 
    'MED' => 'info',
    'DEL' => 'success'
  }
  def class_for_player(player)
    CLASS_FOR_POSITION[player.position.code]
  end
  def class_for_record(record)
    if record.starting?
      CLASS_FOR_POSITION[record.player.position.code]
    else
      'default'
    end
  end

  def player_rating(player)
    if player.rating_count == 0
      '-'
    else
      player.rating_avg
    end
  end
end

app/views/players/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
<div class="form-group">
  <%= f.label :name, 'Name' %>
  <%= f.text_field :name, class: "form-control", placeholder: 'Introduzca el nombre del jugador' %>
</div>
<div class="form-group">
  <%= f.label :number, 'Number' %>
  <%= f.text_field :number, class: "form-control", placeholder: 'Enter the number of the player' %>
</div>
<div class="form-group">
  <%= f.label :position_id, 'Position' %>
  <%= f.select :position_id, @positions, {include_blank: "Select a position"}, { class: "form-control" } %>
</div>
<%= f.submit 'Save', class: 'btn btn-default' %>

app/views/players/_show_admin_menu.html.erb
<section class="panel panel-primary">
  <section class="panel-heading">
    <h3 class="panel-title">Administration</h3>
  </section>
  <section class="panel-body">
    <ul class="list-inline">
      <li>
        <a href="<%= edit_team_player_path(@team, @player) %>">
          <i class="fa fa-edit"></i>
          Edit
        </a>
      </li>
      <li>
        <%= link_to content_tag(:i, " ", class: "fa fa-trash-o") << "Delete", team_player_path(@team, @player), method: :delete, data: { confirm: 'Are you sure?' } %>
      </li>
    </ul>
  </section>
</section>

app/views/players/edit.html.erb
<%= form_for [@team, @player], html: { role: 'form' } do |f| %>
  <%= render 'fields', f: f %>
<% end %>

app/views/players/index.html.erb
<% provide(:title, "Jugadores") %>

<section id="players">
  <header class="page-header">
    <h1>Jugadores <small class="hidden-xs">Todos</small></h1>
  </header>
  <nav>
    <ol class="breadcrumb">
      <li class="active">Jugadores</li>
    </ol>
  </nav>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#round-filters">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand visible-xs" href="#">Filtros: </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse text-right" id="round-filters">
        <ul class="nav navbar-nav">
          <li class="<%= 'active' unless params[:position] %>"><a href="<%= players_path %>">Todos</a></li>
          <li class="<%= 'active' if params[:position] == "1" %>"><a href="<%= players_path(position: 1) %>">POR</a></li>
          <li class="<%= 'active' if params[:position] == "2" %>"><a href="<%= players_path(position: 2) %>">DEF</a></li>
          <li class="<%= 'active' if params[:position] == "3" %>"><a href="<%= players_path(position: 3) %>">MED</a></li>
          <li class="<%= 'active' if params[:position] == "4" %>"><a href="<%= players_path(position: 4) %>">DEL</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th></th>
          <th class="hidden-xs">Selección</th>
          <th>#</th>
          <th>Rol</th>
          <th>Nombre</th>
          <th>Nota</th>
          <th class="hidden-xs">Votos</th>
          <th class="hidden-xs">Partidos</th>
          <th class="hidden-xs">Minutos</th>
          <th class="hidden-xs">Goles</th>
          <th class="hidden-xs">Amarillas</th>
          <th class="hidden-xs">Rojas</th>
        </tr>
      </thead>
      <tbody>
        <% @players.each do |player| %>
        <tr class="<%= 'active' if player.team_id.even? %>">
          <td><%= image_for(player.team, :small) %></td>
          <td class="hidden-xs"><%= link_to player.team, team_path(player.team) %></td>
          <td><%= player.number %></td>
          <td><%= link_to player.position, players_path(position: player.position) %></td>
          <td><%= link_to player, team_player_path(player.team, player) %></td>
          <td>
            <span class="label label-<%= class_for_rating(player.rating_avg) %>">
              <%= player_rating(player) %>
            </span>
          </td>
          <td class="hidden-xs"><%= player.rating_count %></td>
          <td class="hidden-xs"><%= player.games_played %></td>
          <td class="hidden-xs"><%= player.minutes %></td>
          <td class="hidden-xs"><%= player.goals %></td>
          <td class="hidden-xs"><%= player.yellow_cards %></td>
          <td class="hidden-xs"><%= player.red_cards %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="container text-center">
    <%= will_paginate @players, previous_label: content_tag(:i, '', class: 'fa fa-chevron-left'), next_label: content_tag(:i, '', class: 'fa fa-chevron-right'), renderer: BootstrapPagination::Rails %>
  </div>
</section>

app/views/players/new.html.erb
<%= form_for [@team, @player], html: { role: 'form' } do |f| %>
  <%= render 'fields', f: f %>
<% end %>

app/views/players/show.html.erb
<% provide(:title, @player) %>

<section id="player_<%= @player.id %>">
  <header class="page-header">
    <h1><%= "##{@player.number} #{@player}" %> <small class="hidden-xs"><%= image_for(@team, :medium) %> <%= @team %></small></h1>
  </header>

  <%= render 'show_admin_menu' if signed_in_as_admin? %>
  <nav>
    <ol class="breadcrumb">
      <li>
        <a href="<%= teams_path %>">Selecciones</a>
      </li>
      <li>
        <a href="<%= team_path(@team) %>"><%= @team %></a>
      </li>
      <li class="active"><%= @player %></li>
    </ol>
  </nav>
  <div class="table-responsive">
    <table class="table table-hover tablesorter" id="player-games-table">
      <thead>
        <tr>
          <th class="sorter-false" data-sorter="false">Fecha</th>
          <th class="sorter-false" data-sorter="false">Partido</th>
          <th>Nota</th>
          <th>Votos</th>
          <th>Minutos</th>
          <th>Goles</th>
          <th>Amarillas</th>
          <th>Rojas</th>
        </tr>
      </thead>
      <tbody>
        <% @player.performance_records.each do |record| %>
        <tr>
          <td><%= record.game.date.to_s(:month_year_and_time) %></td>
          <td>
            <a href="<%= game_path(record.game) %>">
              <%= image_for(record.game.home_team, :small) %>
              <%= record.game %>
              <%= image_for(record.game.away_team, :small) %>
            </a>
          </td>
          <td><%= record.rating_avg %></td>
          <td><%= record.rating_count %></td>
          <td><%= record.minutes %></td>
          <td><%= record.goals %></td>
          <td><%= record.yellow_cards %></td>
          <td><%= record.red_cards %></td>
        </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td>-</td>
          <td>Total</td>
          <td><%= @player.rating_avg %></td>
          <td><%= @player.rating_count %></td>
          <td><%= @player.minutes %></td>
          <td><%= @player.goals %></td>
          <td><%= @player.yellow_cards %></td>
          <td><%= @player.red_cards %></td>
        </tr>
      </tfoot>
    </table>
  </div>
</section>