config/routes.rb
Brazil2014::Application.routes.draw do
  root 'games#index'

  get  'auth/twitter/callback', to: 'sessions#create'
  get  'auth/failure',        to: redirect('/')  
  get  'signout',             to: 'sessions#destroy',       as: 'signout'
  get  'auth/twitter',                                      as: 'signin'
  get  'cookies',             to: 'static_pages#cookies',   as: 'cookies'

  get  'players',             to: 'players#index',          as: 'players'

  post 'games/:game_id/performance_records/:performance_record_id/ratings/', to: 'ratings#create', as: 'game_performance_record_ratings'

  get 'users/:user_id/games/:game_id', to: 'ratings#index', as: 'user_game'
  resources :users, only: :show

  resources :teams do
    resources :players, except: :index
  end

  resources :games do
    resources :performance_records, only: [:new, :create, :destroy]
  end

end

app/views/layouts/_favicons.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
<link rel="icon" type="image/png" href="/favicon-196x196.png" sizes="196x196">
<link rel="icon" type="image/png" href="/favicon-160x160.png" sizes="160x160">
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<meta name="msapplication-TileColor" content="#ffc40d">
<meta name="msapplication-TileImage" content="/mstile-144x144.png">

app/views/layouts/_footer.html.erb
<footer class="footer text-center">
  <ul class="list-inline">
    <li>
      <a href="https://twitter.com/NotasDelMundial" class="twitter-follow-button" data-show-count="false" data-lang="es">Seguir a @NotasDelMundial</a>
    </li>
    <li class="facebook-button">
      <div class="fb-like" data-href="<%= root_url %>" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
    </li>
  </ul>
  <ul class="list-inline">
    <li>
      Flags from
      <%= link_to 'BannerFlow', 'http://www.bannerflow.com' %>
    </li>
    <li>
       © Las Notas del Mundial by <%= link_to "Antonio Borrero Granell", "http://linkedin.com/in/antoniobg87" %>
    </li>
  </ul>
</footer>

app/views/layouts/_guest_navbar.html.erb
<nav class="navbar navbar-brazil navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#brazil-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <%= image_tag(image_path('logo-top.png'), style: "padding: 0; margin: 0;") %>
        Las Notas de Brasil 2<span class="maki-soccer"></span>14
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="brazil-navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= games_path %>"><i class="fa fa-calendar"></i> Partidos</a></li>
        <li><a href="<%= teams_path %>"><i class="fa fa-flag"></i> Selecciones</a></li>
        <li><a href="<%= players_path %>"><i class="fa fa-user"></i> Jugadores</a></li>
        <li><a href="<%= signin_path %>"><i class="fa fa-sign-in"> Entrar</i></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

app/views/layouts/_user_navbar.html.erb
<nav class="navbar navbar-brazil navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#brazil-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <%= image_tag(image_path('logo-top.png'), style: "padding: 0; margin: 0;") %>
        Las Notas de Brasil 2<span class="maki-soccer"></span>14
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse text-right" id="brazil-navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= games_path %>"><i class="fa fa-calendar"></i> Partidos</a></li>
        <li><a href="<%= teams_path %>"><i class="fa fa-flag"></i> Selecciones</a></li>
        <li><a href="<%= players_path %>"><i class="fa fa-user"></i> Jugadores</a></li>
        <li><a href="<%= user_path(current_user) %>"><i class="fa fa-star"></i> Mis Notas</a></li>
        <li>
          <%= image_tag(current_user.image, class: "img-circle hidden-xs", alt: current_user.username, title: current_user.username) %> 
        </li>
        <li><a href="<%= signout_path %>"><i class="fa fa-power-off"></i> Salir</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <title><%= full_title(yield(:title)) %></title>
  <title>Las Notas de Brasil 2014 - Puntúa la actuación de los jugadores en el Mundial</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Puntúa la actuación de los jugadores en el Mundial de Brasil 2014 y compárte tus impresiones con tus amigos.">
  <%= yield(:extra_meta) if content_for?(:extra_meta) %>
  
  <!-- Open Graph -->
  <meta property="og:locale" content="es_ES" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="<%= full_title(yield(:title)) %>" />
  <meta property="og:description" content="Evalúa la actuación de los jugadores y las selecciones en el Mundial de Brasil 2014 y comparte tus impresiones con tus amigos." />
  <meta property="og:url" content="http://lasnotasdelmundial.com/" />
  <meta property="og:site_name" content="Las Notas del Mundial" />
  <meta property="og:image" content="<%= image_path('logo-original.png') %>" />

  <%= render 'layouts/favicons' %>
  <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= twitter_bootstrap_stylesheet_link_tag :netdna, force: true, version: "3.1.1" %>
  <%= stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css", :cache => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= twitter_bootstrap_javascript_include_tag :netdna, force: true, version: "3.1.1"  %>
  <script>
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_ES/sdk.js#xfbml=1&appId=451436034959157&version=v2.0";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>
  <script>
    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
  </script>
  <% if cookies[:visits] == 0 %>
    <%= render 'shared/launch_modal' %>
  <% end %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <div id="fb-root"></div>
  <header>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <% if signed_in? %>
          <%= render 'layouts/user_navbar' %>
        <% else %>
          <%= render 'layouts/guest_navbar' %>
        <% end %>
      </div>
    </nav>
  </header>
  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
     <%= value %>
  </div>
  <% end %>  
  <section class="container">
    <%= yield %>
    <%= render 'shared/signin_modal' %>
  </section>
  <%= render 'layouts/footer' %>
  <%= render 'cookies_eu/cookies_eu', link: cookies_path %>
  <%= render 'shared/google_analytics' if Rails.env.production? %>   
</body>
</html>